"""Добавил уникальность в links

Revision ID: 21c1ff2e1401
Revises: c24982b079a1
Create Date: 2026-07-12 17:42:49.433573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c1ff2e1401'
down_revision: Union[str, Sequence[str], None] = 'c24982b079a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'links', ['car_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='unique')
    # ### end Alembic commands ###
