"""изменил ключ

Revision ID: 7b1126ede4cd
Revises: 851de5bff5b3
Create Date: 2026-07-13 20:50:59.444756

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7b1126ede4cd'
down_revision: Union[str, Sequence[str], None] = '851de5bff5b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('car_image_car_id_fkey'), 'car_image', type_='foreignkey')
    op.create_foreign_key(None, 'car_image', 'cars', ['car_id'], ['car_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car_image', type_='foreignkey')
    op.create_foreign_key(op.f('car_image_car_id_fkey'), 'car_image', 'cars', ['car_id'], ['id'])
    # ### end Alembic commands ###
