"""добавил таблицу cars

Revision ID: 851de5bff5b3
Revises: 21c1ff2e1401
Create Date: 2026-07-13 20:43:04.487685

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '851de5bff5b3'
down_revision: Union[str, Sequence[str], None] = '21c1ff2e1401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('generation', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('body_type', sa.String(length=50), nullable=False),
    sa.Column('engine_volume', sa.Float(), nullable=True),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('transmission', sa.String(length=50), nullable=False),
    sa.Column('drive', sa.String(length=50), nullable=False),
    sa.Column('steering', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('customs_cleared', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('seller_phone', sa.String(length=32), nullable=True),
    sa.Column('options', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_body_type'), 'cars', ['body_type'], unique=False)
    op.create_index(op.f('ix_cars_brand'), 'cars', ['brand'], unique=False)
    op.create_index(op.f('ix_cars_car_id'), 'cars', ['car_id'], unique=True)
    op.create_index(op.f('ix_cars_city'), 'cars', ['city'], unique=False)
    op.create_index(op.f('ix_cars_created_at'), 'cars', ['created_at'], unique=False)
    op.create_index(op.f('ix_cars_drive'), 'cars', ['drive'], unique=False)
    op.create_index(op.f('ix_cars_model'), 'cars', ['model'], unique=False)
    op.create_index(op.f('ix_cars_price'), 'cars', ['price'], unique=False)
    op.create_index(op.f('ix_cars_transmission'), 'cars', ['transmission'], unique=False)
    op.create_index(op.f('ix_cars_url'), 'cars', ['url'], unique=False)
    op.create_index(op.f('ix_cars_year'), 'cars', ['year'], unique=False)
    op.create_table('car_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('links', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('links', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('links_car_id_key'), 'links', type_='unique')
    op.create_index(op.f('ix_links_car_id'), 'links', ['car_id'], unique=True)
    op.create_index(op.f('ix_links_created_at'), 'links', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_created_at'), table_name='links')
    op.drop_index(op.f('ix_links_car_id'), table_name='links')
    op.create_unique_constraint(op.f('links_car_id_key'), 'links', ['car_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('links', 'updated_at')
    op.drop_column('links', 'is_active')
    op.drop_table('car_image')
    op.drop_index(op.f('ix_cars_year'), table_name='cars')
    op.drop_index(op.f('ix_cars_url'), table_name='cars')
    op.drop_index(op.f('ix_cars_transmission'), table_name='cars')
    op.drop_index(op.f('ix_cars_price'), table_name='cars')
    op.drop_index(op.f('ix_cars_model'), table_name='cars')
    op.drop_index(op.f('ix_cars_drive'), table_name='cars')
    op.drop_index(op.f('ix_cars_created_at'), table_name='cars')
    op.drop_index(op.f('ix_cars_city'), table_name='cars')
    op.drop_index(op.f('ix_cars_car_id'), table_name='cars')
    op.drop_index(op.f('ix_cars_brand'), table_name='cars')
    op.drop_index(op.f('ix_cars_body_type'), table_name='cars')
    op.drop_table('cars')
    # ### end Alembic commands ###
