"""init refresh tokens schema

Revision ID: e0db0fbcfab4
Revises: f45df0d9bfd8
Create Date: 2026-07-18 21:40:24.955953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0db0fbcfab4'
down_revision: Union[str, Sequence[str], None] = 'f45df0d9bfd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expired', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('favorites', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_column('favorites', 'id')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
