"""init currency schema

Revision ID: ef23abe5284d
Revises: e0db0fbcfab4
Create Date: 2026-07-19 15:27:06.541596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef23abe5284d'
down_revision: Union[str, Sequence[str], None] = 'e0db0fbcfab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.Enum('USD', 'EUR', 'KZT', 'RUB', name='currencytype'), nullable=False),
    sa.Column('quote_currency', sa.Enum('USD', 'EUR', 'KZT', 'RUB', name='currencytype'), nullable=False),
    sa.Column('rate', sa.DECIMAL(), nullable=False),
    sa.Column('rate_updated_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency')
    # ### end Alembic commands ###
