"""add currency to cars

Revision ID: f95ced3560e1
Revises: ef23abe5284d
Create Date: 2026-07-19 20:49:30.881659

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f95ced3560e1'
down_revision: Union[str, Sequence[str], None] = 'ef23abe5284d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('currency', sa.Enum('USD', 'EUR', 'KZT', 'RUB', name='currencytype'), server_default='KZT', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'currency')
    # ### end Alembic commands ###
