"""init car views schema

Revision ID: f9beea947d31
Revises: de247ea8b785
Create Date: 2026-07-22 16:12:21.503958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9beea947d31'
down_revision: Union[str, Sequence[str], None] = 'de247ea8b785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.car_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id', 'user_id')
    )
    op.create_index(op.f('ix_car_views_car_id'), 'car_views', ['car_id'], unique=False)
    op.create_index(op.f('ix_car_views_user_id'), 'car_views', ['user_id'], unique=False)
    op.add_column('cars', sa.Column('views', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_favorites_car_id'), 'favorites', ['car_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorites_car_id'), table_name='favorites')
    op.drop_column('cars', 'views')
    op.drop_index(op.f('ix_car_views_user_id'), table_name='car_views')
    op.drop_index(op.f('ix_car_views_car_id'), table_name='car_views')
    op.drop_table('car_views')
    # ### end Alembic commands ###
